project:
  logger:
    level: 1
  services:
    component_ping:
      name: component_ping
      version: v1
    component_pong:
      name: component_pong
      version: v1
    trellis-postapi:
      name: trellis-postapi
      version: v1
      options:
        http:
          postapi: "/v1"
          static_path: "/"
          static_redirect: "/text/"
          static_root: "../static_server/root"
          address: ":8080"
          # shutdown-timeout: 30s
          pprof:
            enabled: true
            authorization: "test" ## default no need header: Authorization
            prefix: / ## default /
        gin_mode: debug
        apis:
          type: file ## default file | mysql
          file:
            trellis-test:
              api: trellis.ping
              service_name: component_ping
              service_version: v1
              topic: ping
