// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trellis.tech/trellis.v1/proto/node.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeType int32

const (
	NodeType_Direct     NodeType = 0
	NodeType_Random     NodeType = 1
	NodeType_Consistent NodeType = 2
	NodeType_RoundRobin NodeType = 3
)

var NodeType_name = map[int32]string{
	0: "Direct",
	1: "Random",
	2: "Consistent",
	3: "RoundRobin",
}

var NodeType_value = map[string]int32{
	"Direct":     0,
	"Random":     1,
	"Consistent": 2,
	"RoundRobin": 3,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}

func (NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8475b92af2a52f7b, []int{0}
}

type Protocol int32

const (
	// 本地服务，直接访问
	Protocol_LOCAL Protocol = 0
	// RPC协议的服务
	Protocol_GRPC Protocol = 1
	// HTTP协议的服务
	Protocol_HTTP Protocol = 2
	// HTTP 3.0协议的服务
	Protocol_QUIC Protocol = 3
)

var Protocol_name = map[int32]string{
	0: "LOCAL",
	1: "GRPC",
	2: "HTTP",
	3: "QUIC",
}

var Protocol_value = map[string]int32{
	"LOCAL": 0,
	"GRPC":  1,
	"HTTP":  2,
	"QUIC":  3,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}

func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8475b92af2a52f7b, []int{1}
}

type BaseNode struct {
	// @gotags: yaml:"weight"
	Weight uint32 `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty" yaml:"weight"`
	// @gotags: yaml:"value"
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" yaml:"value"`
	// @gotags: yaml:"ttl"
	TTL uint64 `protobuf:"varint,3,opt,name=TTL,proto3" json:"TTL,omitempty" yaml:"ttl"`
	// @gotags: yaml:"heartbeat"
	Heartbeat uint64 `protobuf:"varint,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty" yaml:"heartbeat"`
	// @gotags: yaml:"protocol"
	Protocol Protocol `protobuf:"varint,5,opt,name=protocol,proto3,enum=node.Protocol" json:"protocol,omitempty" yaml:"protocol"`
	// @gotags: protobuf:"-" json:"-" yaml:"-"
	Number               uint32   `protobuf:"-" json:"-" yaml:"-"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseNode) Reset()         { *m = BaseNode{} }
func (m *BaseNode) String() string { return proto.CompactTextString(m) }
func (*BaseNode) ProtoMessage()    {}
func (*BaseNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_8475b92af2a52f7b, []int{0}
}

func (m *BaseNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseNode.Unmarshal(m, b)
}
func (m *BaseNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseNode.Marshal(b, m, deterministic)
}
func (m *BaseNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseNode.Merge(m, src)
}
func (m *BaseNode) XXX_Size() int {
	return xxx_messageInfo_BaseNode.Size(m)
}
func (m *BaseNode) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseNode.DiscardUnknown(m)
}

var xxx_messageInfo_BaseNode proto.InternalMessageInfo

func (m *BaseNode) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *BaseNode) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *BaseNode) GetTTL() uint64 {
	if m != nil {
		return m.TTL
	}
	return 0
}

func (m *BaseNode) GetHeartbeat() uint64 {
	if m != nil {
		return m.Heartbeat
	}
	return 0
}

func (m *BaseNode) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_LOCAL
}

func (m *BaseNode) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterEnum("node.NodeType", NodeType_name, NodeType_value)
	proto.RegisterEnum("node.Protocol", Protocol_name, Protocol_value)
	proto.RegisterType((*BaseNode)(nil), "node.BaseNode")
}

func init() {
	proto.RegisterFile("trellis.tech/trellis.v1/proto/node.proto", fileDescriptor_8475b92af2a52f7b)
}

var fileDescriptor_8475b92af2a52f7b = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xbb, 0x4d, 0x1a, 0xd2, 0x81, 0xb7, 0x2c, 0xcb, 0x8b, 0xec, 0xc1, 0x43, 0x10, 0xc4,
	0xd0, 0x43, 0x8b, 0xf6, 0xe8, 0xc9, 0x46, 0x50, 0x21, 0xd4, 0xb8, 0xc4, 0x8b, 0xb7, 0xfc, 0x19,
	0x9a, 0x60, 0xba, 0x5b, 0x92, 0x4d, 0xc5, 0xef, 0xe4, 0x87, 0x94, 0xdd, 0xb4, 0x7a, 0xf2, 0xb2,
	0xfc, 0x7e, 0xcf, 0x1e, 0xe6, 0x99, 0x81, 0x50, 0xb7, 0xd8, 0x34, 0x75, 0xb7, 0xd0, 0x58, 0x54,
	0xcb, 0x93, 0x1c, 0xae, 0x97, 0xfb, 0x56, 0x69, 0xb5, 0x94, 0xaa, 0xc4, 0x85, 0x45, 0xe6, 0x1a,
	0xbe, 0xf8, 0x22, 0xe0, 0xaf, 0xb3, 0x0e, 0x37, 0xaa, 0x44, 0x76, 0x06, 0xde, 0x07, 0xd6, 0xdb,
	0x4a, 0x73, 0x12, 0x90, 0xf0, 0x9f, 0x38, 0x1a, 0xfb, 0x0f, 0x93, 0x43, 0xd6, 0xf4, 0xc8, 0xc7,
	0x01, 0x09, 0xa7, 0x62, 0x10, 0x46, 0xc1, 0x49, 0xd3, 0x98, 0x3b, 0x01, 0x09, 0x5d, 0x61, 0x90,
	0x9d, 0xc3, 0xb4, 0xc2, 0xac, 0xd5, 0x39, 0x66, 0x9a, 0xbb, 0x36, 0xff, 0x0d, 0xd8, 0x1c, 0x7c,
	0x3b, 0xb9, 0x50, 0x0d, 0x9f, 0x04, 0x24, 0x9c, 0xdd, 0xcc, 0x16, 0xb6, 0x4f, 0x72, 0x4c, 0xc5,
	0xcf, 0xbf, 0x69, 0xb2, 0xe9, 0x77, 0x39, 0xb6, 0xdc, 0x1b, 0x9a, 0x0c, 0x36, 0x5f, 0x83, 0x6f,
	0x9a, 0xa6, 0x9f, 0x7b, 0x64, 0x00, 0xde, 0x7d, 0xdd, 0x62, 0xa1, 0xe9, 0xc8, 0xb0, 0xc8, 0x64,
	0xa9, 0x76, 0x94, 0xb0, 0x19, 0x40, 0xa4, 0x64, 0x57, 0x77, 0x1a, 0xa5, 0xa6, 0x63, 0xe3, 0x42,
	0xf5, 0xb2, 0x14, 0x2a, 0xaf, 0x25, 0x75, 0xe6, 0x2b, 0xf0, 0x4f, 0x13, 0xd9, 0x14, 0x26, 0xf1,
	0x73, 0x74, 0x17, 0xd3, 0x11, 0xf3, 0xc1, 0x7d, 0x10, 0x49, 0x44, 0x89, 0xa1, 0xc7, 0x34, 0x4d,
	0xe8, 0xd8, 0xd0, 0xcb, 0xeb, 0x53, 0x44, 0x9d, 0xf5, 0xd5, 0xdb, 0xe5, 0x9f, 0x97, 0x7d, 0xdf,
	0xda, 0xbb, 0xde, 0x9a, 0x27, 0xf7, 0xec, 0x0e, 0xab, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa,
	0x9e, 0x61, 0x4e, 0x89, 0x01, 0x00, 0x00,
}
