// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: trellis.tech/trellis.v1/proto/node.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_NODE_TYPE_DIRECT     NodeType = 0
	NodeType_NODE_TYPE_RANDOM     NodeType = 1
	NodeType_NODE_TYPE_CONSISTENT NodeType = 2
	NodeType_NODE_TYPE_ROUNDROBIN NodeType = 3
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_DIRECT",
		1: "NODE_TYPE_RANDOM",
		2: "NODE_TYPE_CONSISTENT",
		3: "NODE_TYPE_ROUNDROBIN",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_DIRECT":     0,
		"NODE_TYPE_RANDOM":     1,
		"NODE_TYPE_CONSISTENT": 2,
		"NODE_TYPE_ROUNDROBIN": 3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_trellis_tech_trellis_v1_proto_node_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_trellis_tech_trellis_v1_proto_node_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_trellis_tech_trellis_v1_proto_node_proto_rawDescGZIP(), []int{0}
}

type Protocol int32

const (
	// 本地服务，直接访问
	Protocol_PROTOCOL_LOCAL Protocol = 0
	// RPC协议的服务
	Protocol_PROTOCOL_GRPC Protocol = 1
	// HTTP协议的服务
	Protocol_PROTOCOL_HTTP Protocol = 2
	// HTTP 3.0协议的服务
	Protocol_PROTOCOL_QUIC Protocol = 3
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_LOCAL",
		1: "PROTOCOL_GRPC",
		2: "PROTOCOL_HTTP",
		3: "PROTOCOL_QUIC",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_LOCAL": 0,
		"PROTOCOL_GRPC":  1,
		"PROTOCOL_HTTP":  2,
		"PROTOCOL_QUIC":  3,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_trellis_tech_trellis_v1_proto_node_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_trellis_tech_trellis_v1_proto_node_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_trellis_tech_trellis_v1_proto_node_proto_rawDescGZIP(), []int{1}
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"weight" yaml:"weight"
	Weight uint32 `protobuf:"varint,1,opt,name=weight,proto3" json:"weight" yaml:"weight"`
	// @gotags: json:"value" yaml:"value"
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value" yaml:"value"`
	// @gotags: json:"ttl" yaml:"ttl"
	TTL uint64 `protobuf:"varint,3,opt,name=TTL,proto3" json:"ttl" yaml:"ttl"`
	// @gotags: json:"heartbeat" yaml:"heartbeat"
	Heartbeat uint64 `protobuf:"varint,4,opt,name=heartbeat,proto3" json:"heartbeat" yaml:"heartbeat"`
	// @gotags: json:"protocol" yaml:"protocol"
	Protocol Protocol `protobuf:"varint,5,opt,name=protocol,proto3,enum=node.Protocol" json:"protocol" yaml:"protocol"`
	// @gotags: protobuf:"-" json:"-" yaml:"-"
	Number uint32 `protobuf:"-" json:"-" yaml:"-"`
	// @gotags: json:"metadata" yaml:"metadata"
	Metadata map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" yaml:"metadata"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trellis_tech_trellis_v1_proto_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_trellis_tech_trellis_v1_proto_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_trellis_tech_trellis_v1_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Node) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Node) GetTTL() uint64 {
	if x != nil {
		return x.TTL
	}
	return 0
}

func (x *Node) GetHeartbeat() uint64 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *Node) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_LOCAL
}

func (x *Node) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Node) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_trellis_tech_trellis_v1_proto_node_proto protoreflect.FileDescriptor

var file_trellis_tech_trellis_v1_proto_node_proto_rawDesc = []byte{
	0x0a, 0x28, 0x74, 0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x74,
	0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x22, 0x9b, 0x02, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x54, 0x4c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x54, 0x54, 0x4c, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x6a,
	0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x4e, 0x4f,
	0x44, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x41,
	0x4e, 0x44, 0x4f, 0x4d, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x49, 0x53, 0x54, 0x45, 0x4e, 0x54, 0x10, 0x02,
	0x12, 0x18, 0x0a, 0x14, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f,
	0x55, 0x4e, 0x44, 0x52, 0x4f, 0x42, 0x49, 0x4e, 0x10, 0x03, 0x2a, 0x57, 0x0a, 0x08, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43,
	0x4f, 0x4c, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x47, 0x52, 0x50, 0x43, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x48, 0x54, 0x54, 0x50, 0x10, 0x02,
	0x12, 0x11, 0x0a, 0x0d, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x51, 0x55, 0x49,
	0x43, 0x10, 0x03, 0x42, 0x27, 0x5a, 0x25, 0x74, 0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x74,
	0x65, 0x63, 0x68, 0x2f, 0x74, 0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x3b, 0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trellis_tech_trellis_v1_proto_node_proto_rawDescOnce sync.Once
	file_trellis_tech_trellis_v1_proto_node_proto_rawDescData = file_trellis_tech_trellis_v1_proto_node_proto_rawDesc
)

func file_trellis_tech_trellis_v1_proto_node_proto_rawDescGZIP() []byte {
	file_trellis_tech_trellis_v1_proto_node_proto_rawDescOnce.Do(func() {
		file_trellis_tech_trellis_v1_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_trellis_tech_trellis_v1_proto_node_proto_rawDescData)
	})
	return file_trellis_tech_trellis_v1_proto_node_proto_rawDescData
}

var file_trellis_tech_trellis_v1_proto_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_trellis_tech_trellis_v1_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trellis_tech_trellis_v1_proto_node_proto_goTypes = []interface{}{
	(NodeType)(0), // 0: node.NodeType
	(Protocol)(0), // 1: node.Protocol
	(*Node)(nil),  // 2: node.Node
	nil,           // 3: node.Node.MetadataEntry
}
var file_trellis_tech_trellis_v1_proto_node_proto_depIdxs = []int32{
	1, // 0: node.Node.protocol:type_name -> node.Protocol
	3, // 1: node.Node.metadata:type_name -> node.Node.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trellis_tech_trellis_v1_proto_node_proto_init() }
func file_trellis_tech_trellis_v1_proto_node_proto_init() {
	if File_trellis_tech_trellis_v1_proto_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trellis_tech_trellis_v1_proto_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trellis_tech_trellis_v1_proto_node_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trellis_tech_trellis_v1_proto_node_proto_goTypes,
		DependencyIndexes: file_trellis_tech_trellis_v1_proto_node_proto_depIdxs,
		EnumInfos:         file_trellis_tech_trellis_v1_proto_node_proto_enumTypes,
		MessageInfos:      file_trellis_tech_trellis_v1_proto_node_proto_msgTypes,
	}.Build()
	File_trellis_tech_trellis_v1_proto_node_proto = out.File
	file_trellis_tech_trellis_v1_proto_node_proto_rawDesc = nil
	file_trellis_tech_trellis_v1_proto_node_proto_goTypes = nil
	file_trellis_tech_trellis_v1_proto_node_proto_depIdxs = nil
}
