// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trellis.tech/trellis.v1/proto/server.proto

package server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	message "trellis.tech/trellis.v1/pkg/message"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_All  Type = 0
	Type_HTTP Type = 1
	Type_GRPC Type = 2
)

var Type_name = map[int32]string{
	0: "All",
	1: "HTTP",
	2: "GRPC",
}

var Type_value = map[string]int32{
	"All":  0,
	"HTTP": 1,
	"GRPC": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ba7fd9ea3c4ff36f, []int{0}
}

func init() {
	proto.RegisterEnum("grpc.Type", Type_name, Type_value)
}

func init() {
	proto.RegisterFile("trellis.tech/trellis.v1/proto/server.proto", fileDescriptor_ba7fd9ea3c4ff36f)
}

var fileDescriptor_ba7fd9ea3c4ff36f = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2a, 0x29, 0x4a, 0xcd,
	0xc9, 0xc9, 0x2c, 0xd6, 0x2b, 0x49, 0x4d, 0xce, 0xd0, 0x87, 0x71, 0xca, 0x0c, 0xf5, 0x0b, 0x8a,
	0xf2, 0x4b, 0xf2, 0xf5, 0x8b, 0x53, 0x8b, 0xca, 0x52, 0x8b, 0xf4, 0xc0, 0x1c, 0x21, 0x96, 0xf4,
	0xa2, 0x82, 0x64, 0x29, 0x6d, 0xfc, 0x3a, 0x72, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x21, 0x5a,
	0xb4, 0x94, 0xb9, 0x58, 0x42, 0x2a, 0x0b, 0x52, 0x85, 0xd8, 0xb9, 0x98, 0x1d, 0x73, 0x72, 0x04,
	0x18, 0x84, 0x38, 0xb8, 0x58, 0x3c, 0x42, 0x42, 0x02, 0x04, 0x18, 0x41, 0x2c, 0xf7, 0xa0, 0x00,
	0x67, 0x01, 0x26, 0xa3, 0x5c, 0x2e, 0xf6, 0x10, 0x88, 0x31, 0x42, 0xba, 0x5c, 0x2c, 0xce, 0x89,
	0x39, 0x39, 0x42, 0x02, 0x7a, 0x30, 0x73, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xa4, 0x04,
	0x91, 0x44, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x95, 0x18, 0x84, 0x8c, 0xb9, 0xd8, 0x82, 0x4b,
	0x8a, 0x52, 0x13, 0x73, 0x89, 0xd4, 0xa0, 0xc1, 0x68, 0xc0, 0xe8, 0xa4, 0x1d, 0xa5, 0x89, 0xd3,
	0x0b, 0xd9, 0xe9, 0x50, 0x2f, 0x5b, 0x43, 0xa8, 0x24, 0x36, 0xb0, 0x3f, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0x9e, 0x90, 0x39, 0x28, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrellisClient is the client API for Trellis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrellisClient interface {
	// Call allows a single request to be made
	Call(ctx context.Context, in *message.Request, opts ...grpc.CallOption) (*message.Response, error)
	// Stream is a bidirectional stream
	Stream(ctx context.Context, opts ...grpc.CallOption) (Trellis_StreamClient, error)
}

type trellisClient struct {
	cc *grpc.ClientConn
}

func NewTrellisClient(cc *grpc.ClientConn) TrellisClient {
	return &trellisClient{cc}
}

func (c *trellisClient) Call(ctx context.Context, in *message.Request, opts ...grpc.CallOption) (*message.Response, error) {
	out := new(message.Response)
	err := c.cc.Invoke(ctx, "/grpc.Trellis/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trellisClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Trellis_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Trellis_serviceDesc.Streams[0], "/grpc.Trellis/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &trellisStreamClient{stream}
	return x, nil
}

type Trellis_StreamClient interface {
	Send(*message.Request) error
	Recv() (*message.Response, error)
	grpc.ClientStream
}

type trellisStreamClient struct {
	grpc.ClientStream
}

func (x *trellisStreamClient) Send(m *message.Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *trellisStreamClient) Recv() (*message.Response, error) {
	m := new(message.Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrellisServer is the server API for Trellis service.
type TrellisServer interface {
	// Call allows a single request to be made
	Call(context.Context, *message.Request) (*message.Response, error)
	// Stream is a bidirectional stream
	Stream(Trellis_StreamServer) error
}

// UnimplementedTrellisServer can be embedded to have forward compatible implementations.
type UnimplementedTrellisServer struct {
}

func (*UnimplementedTrellisServer) Call(ctx context.Context, req *message.Request) (*message.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (*UnimplementedTrellisServer) Stream(srv Trellis_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterTrellisServer(s *grpc.Server, srv TrellisServer) {
	s.RegisterService(&_Trellis_serviceDesc, srv)
}

func _Trellis_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrellisServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Trellis/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrellisServer).Call(ctx, req.(*message.Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trellis_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrellisServer).Stream(&trellisStreamServer{stream})
}

type Trellis_StreamServer interface {
	Send(*message.Response) error
	Recv() (*message.Request, error)
	grpc.ServerStream
}

type trellisStreamServer struct {
	grpc.ServerStream
}

func (x *trellisStreamServer) Send(m *message.Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *trellisStreamServer) Recv() (*message.Request, error) {
	m := new(message.Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Trellis_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Trellis",
	HandlerType: (*TrellisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Trellis_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Trellis_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "trellis.tech/trellis.v1/proto/server.proto",
}
