// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: trellis.tech/trellis.v1/proto/registry.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	node "trellis.tech/trellis.v1/pkg/node"
	service "trellis.tech/trellis.v1/pkg/service"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterType int32

const (
	RegisterType_REGISTER_TYPE_MEMORY RegisterType = 0
	RegisterType_REGISTER_TYPE_ETCD   RegisterType = 1
)

// Enum value maps for RegisterType.
var (
	RegisterType_name = map[int32]string{
		0: "REGISTER_TYPE_MEMORY",
		1: "REGISTER_TYPE_ETCD",
	}
	RegisterType_value = map[string]int32{
		"REGISTER_TYPE_MEMORY": 0,
		"REGISTER_TYPE_ETCD":   1,
	}
)

func (x RegisterType) Enum() *RegisterType {
	p := new(RegisterType)
	*p = x
	return p
}

func (x RegisterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterType) Descriptor() protoreflect.EnumDescriptor {
	return file_trellis_tech_trellis_v1_proto_registry_proto_enumTypes[0].Descriptor()
}

func (RegisterType) Type() protoreflect.EnumType {
	return &file_trellis_tech_trellis_v1_proto_registry_proto_enumTypes[0]
}

func (x RegisterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterType.Descriptor instead.
func (RegisterType) EnumDescriptor() ([]byte, []int) {
	return file_trellis_tech_trellis_v1_proto_registry_proto_rawDescGZIP(), []int{0}
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service     *service.Service  `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	EventType   service.EventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=service.EventType" json:"event_type,omitempty"`
	ServiceNode *ServiceNode      `protobuf:"bytes,4,opt,name=service_node,json=serviceNode,proto3" json:"service_node,omitempty"`
	Timestamp   int64             `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trellis_tech_trellis_v1_proto_registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_trellis_tech_trellis_v1_proto_registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_trellis_tech_trellis_v1_proto_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Result) GetService() *service.Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Result) GetEventType() service.EventType {
	if x != nil {
		return x.EventType
	}
	return service.EventType_EVENT_TYPE_CREATE
}

func (x *Result) GetServiceNode() *ServiceNode {
	if x != nil {
		return x.ServiceNode
	}
	return nil
}

func (x *Result) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ServiceNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *service.Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Node    *node.Node       `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *ServiceNode) Reset() {
	*x = ServiceNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trellis_tech_trellis_v1_proto_registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNode) ProtoMessage() {}

func (x *ServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_trellis_tech_trellis_v1_proto_registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNode.ProtoReflect.Descriptor instead.
func (*ServiceNode) Descriptor() ([]byte, []int) {
	return file_trellis_tech_trellis_v1_proto_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceNode) GetService() *service.Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceNode) GetNode() *node.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_trellis_tech_trellis_v1_proto_registry_proto protoreflect.FileDescriptor

var file_trellis_tech_trellis_v1_proto_registry_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x74, 0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x74,
	0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x1a, 0x2b, 0x74, 0x72, 0x65, 0x6c, 0x6c, 0x69,
	0x73, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x74, 0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x76,
	0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x28, 0x74, 0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x74,
	0x65, 0x63, 0x68, 0x2f, 0x74, 0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xcf, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x59, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x2a, 0x40, 0x0a, 0x0c,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14,
	0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x45,
	0x4d, 0x4f, 0x52, 0x59, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54,
	0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x54, 0x43, 0x44, 0x10, 0x01, 0x42, 0x2f,
	0x5a, 0x2d, 0x74, 0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x74,
	0x72, 0x65, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x3b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trellis_tech_trellis_v1_proto_registry_proto_rawDescOnce sync.Once
	file_trellis_tech_trellis_v1_proto_registry_proto_rawDescData = file_trellis_tech_trellis_v1_proto_registry_proto_rawDesc
)

func file_trellis_tech_trellis_v1_proto_registry_proto_rawDescGZIP() []byte {
	file_trellis_tech_trellis_v1_proto_registry_proto_rawDescOnce.Do(func() {
		file_trellis_tech_trellis_v1_proto_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_trellis_tech_trellis_v1_proto_registry_proto_rawDescData)
	})
	return file_trellis_tech_trellis_v1_proto_registry_proto_rawDescData
}

var file_trellis_tech_trellis_v1_proto_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_trellis_tech_trellis_v1_proto_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trellis_tech_trellis_v1_proto_registry_proto_goTypes = []interface{}{
	(RegisterType)(0),       // 0: registry.RegisterType
	(*Result)(nil),          // 1: registry.Result
	(*ServiceNode)(nil),     // 2: registry.ServiceNode
	(*service.Service)(nil), // 3: service.Service
	(service.EventType)(0),  // 4: service.EventType
	(*node.Node)(nil),       // 5: node.Node
}
var file_trellis_tech_trellis_v1_proto_registry_proto_depIdxs = []int32{
	3, // 0: registry.Result.service:type_name -> service.Service
	4, // 1: registry.Result.event_type:type_name -> service.EventType
	2, // 2: registry.Result.service_node:type_name -> registry.ServiceNode
	3, // 3: registry.ServiceNode.service:type_name -> service.Service
	5, // 4: registry.ServiceNode.node:type_name -> node.Node
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_trellis_tech_trellis_v1_proto_registry_proto_init() }
func file_trellis_tech_trellis_v1_proto_registry_proto_init() {
	if File_trellis_tech_trellis_v1_proto_registry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trellis_tech_trellis_v1_proto_registry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trellis_tech_trellis_v1_proto_registry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trellis_tech_trellis_v1_proto_registry_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trellis_tech_trellis_v1_proto_registry_proto_goTypes,
		DependencyIndexes: file_trellis_tech_trellis_v1_proto_registry_proto_depIdxs,
		EnumInfos:         file_trellis_tech_trellis_v1_proto_registry_proto_enumTypes,
		MessageInfos:      file_trellis_tech_trellis_v1_proto_registry_proto_msgTypes,
	}.Build()
	File_trellis_tech_trellis_v1_proto_registry_proto = out.File
	file_trellis_tech_trellis_v1_proto_registry_proto_rawDesc = nil
	file_trellis_tech_trellis_v1_proto_registry_proto_goTypes = nil
	file_trellis_tech_trellis_v1_proto_registry_proto_depIdxs = nil
}
