project:
  logger:
    level: 1
  registries:
    test:
      name: test
      type: 1
      endpoint: ["127.0.0.1:2379"]
      timeout: 10s
      server_addr: "http://127.0.0.1:8080/v1"
      retry_times: 1
      watchers:
        -
          name: component_pong
          version: v1
  services:
    component_ping:
      name: component_ping
      version: v1
    trellis-postapi:
      name: trellis-postapi
      version: v1
      options:
        gin_mode: debug
        http:
          postapi: "/v1"
          address: ":8080"
          # shutdown-timeout: 30s
          pprof:
            enabled: true
            authorization: "test" ## default no need header: Authorization
            prefix: / ## default /
          # cors:
        apis:
          file:
            test:
              api: test
              topic: ping
              service_name: component_ping
              service_version: v1