// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trellis.tech/trellis.v1/proto/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	service "trellis.tech/trellis.v1/pkg/service"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Service *service.Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Request payload
	Payload              *Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_57530fd20e3d43b2, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetService() *service.Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Request) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Response struct {
	// @gotags: json:"code"
	Code   int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	ErrMsg string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	// Response payload @gotags: json:"payload"
	Payload              *Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_57530fd20e3d43b2, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Payload struct {
	Header               map[string]string `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_57530fd20e3d43b2, []int{2}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Payload) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "message.Request")
	proto.RegisterType((*Response)(nil), "message.Response")
	proto.RegisterType((*Payload)(nil), "message.Payload")
	proto.RegisterMapType((map[string]string)(nil), "message.Payload.HeaderEntry")
}

func init() {
	proto.RegisterFile("trellis.tech/trellis.v1/proto/message.proto", fileDescriptor_57530fd20e3d43b2)
}

var fileDescriptor_57530fd20e3d43b2 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0xa3, 0x59, 0x3b, 0xf1, 0x50, 0x16, 0xc1, 0x50, 0x3c, 0x94, 0x9e, 0x8a, 0x62,
	0x82, 0xd5, 0x83, 0x7f, 0x6e, 0x82, 0xe0, 0x45, 0x90, 0xf5, 0xe6, 0x45, 0xb6, 0xc9, 0x90, 0x96,
	0xa6, 0xdd, 0xb8, 0xb3, 0x0d, 0xe4, 0x4b, 0xf8, 0x99, 0x25, 0x9b, 0x5d, 0x28, 0x82, 0xf4, 0xb4,
	0xf3, 0x66, 0x7e, 0xb3, 0xf3, 0xe0, 0xc1, 0x95, 0xd1, 0x58, 0x55, 0x2b, 0x4a, 0x0d, 0xe6, 0xcb,
	0xcc, 0x8b, 0xe6, 0x26, 0xab, 0xb5, 0x32, 0x2a, 0xdb, 0x20, 0x91, 0x2c, 0x31, 0xb5, 0x8a, 0x33,
	0x27, 0xc7, 0x07, 0xb6, 0x08, 0x75, 0xb3, 0xca, 0xdd, 0xd6, 0x54, 0x02, 0x13, 0xf8, 0xbd, 0x43,
	0x32, 0xfc, 0x12, 0x98, 0x9b, 0x25, 0xc1, 0x24, 0x98, 0xc5, 0xf3, 0x51, 0xea, 0xd9, 0x8f, 0xfe,
	0x15, 0x1e, 0xe8, 0xd8, 0x5a, 0xb6, 0x95, 0x92, 0x45, 0x32, 0x70, 0xac, 0x77, 0xf3, 0xde, 0xf7,
	0x85, 0x07, 0xa6, 0x39, 0x9c, 0x08, 0xa4, 0x5a, 0x6d, 0x09, 0x39, 0x87, 0xa3, 0x5c, 0x15, 0xfd,
	0x81, 0x50, 0xd8, 0x9a, 0x9f, 0x03, 0x43, 0xad, 0xbf, 0x36, 0x54, 0xda, 0xbf, 0x86, 0x22, 0x42,
	0xad, 0xdf, 0xa8, 0xdc, 0x3f, 0x12, 0x1e, 0x3a, 0xf2, 0x13, 0x00, 0x73, 0x4d, 0x7e, 0x07, 0xd1,
	0x12, 0x65, 0x81, 0x3a, 0x09, 0x26, 0xe1, 0x2c, 0x9e, 0x5f, 0xfc, 0x5d, 0x4b, 0x5f, 0xed, 0xf8,
	0x65, 0x6b, 0x74, 0x2b, 0x1c, 0xdb, 0x59, 0x5b, 0xa8, 0xa2, 0xb5, 0x1e, 0x4e, 0x85, 0xad, 0xc7,
	0x0f, 0x10, 0xef, 0xa1, 0x7c, 0x04, 0xe1, 0x1a, 0x5b, 0x6b, 0x7e, 0x28, 0xba, 0x92, 0x9f, 0xc1,
	0x71, 0x23, 0xab, 0x1d, 0x3a, 0xe7, 0xbd, 0x78, 0x1c, 0xdc, 0x07, 0xcf, 0xd7, 0x9f, 0xff, 0xe7,
	0xb0, 0x2e, 0x7d, 0x76, 0x4f, 0xee, 0x5d, 0x44, 0x36, 0x8e, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x65, 0x77, 0x83, 0xd1, 0xf3, 0x01, 0x00, 0x00,
}
