// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trellis.tech/trellis.v1/proto/service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	node "trellis.tech/trellis.v1/pkg/node"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_create EventType = 0
	EventType_delete EventType = 1
	EventType_update EventType = 2
)

var EventType_name = map[int32]string{
	0: "create",
	1: "delete",
	2: "update",
}

var EventType_value = map[string]int32{
	"create": 0,
	"delete": 1,
	"update": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_462d1b47d56d4d85, []int{0}
}

type Service struct {
	// @gotags: yaml:"domain"
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty" yaml:"domain"`
	// @gotags: yaml:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`
	// @gotags: yaml:"version"
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty" yaml:"version"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_462d1b47d56d4d85, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ServiceNode struct {
	Service              *Service   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Node                 *node.Node `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceNode) Reset()         { *m = ServiceNode{} }
func (m *ServiceNode) String() string { return proto.CompactTextString(m) }
func (*ServiceNode) ProtoMessage()    {}
func (*ServiceNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_462d1b47d56d4d85, []int{1}
}

func (m *ServiceNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceNode.Unmarshal(m, b)
}
func (m *ServiceNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceNode.Marshal(b, m, deterministic)
}
func (m *ServiceNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceNode.Merge(m, src)
}
func (m *ServiceNode) XXX_Size() int {
	return xxx_messageInfo_ServiceNode.Size(m)
}
func (m *ServiceNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceNode.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceNode proto.InternalMessageInfo

func (m *ServiceNode) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *ServiceNode) GetNode() *node.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func init() {
	proto.RegisterEnum("service.EventType", EventType_name, EventType_value)
	proto.RegisterType((*Service)(nil), "service.Service")
	proto.RegisterType((*ServiceNode)(nil), "service.ServiceNode")
}

func init() {
	proto.RegisterFile("trellis.tech/trellis.v1/proto/service.proto", fileDescriptor_462d1b47d56d4d85)
}

var fileDescriptor_462d1b47d56d4d85 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0xb4, 0xeb, 0xd2, 0xb2, 0xaf, 0x97, 0xf2, 0x0e, 0x52, 0x3c, 0x88, 0xec, 0x69, 0x59, 0x31,
	0xc1, 0xf5, 0xe8, 0x4d, 0xf0, 0xaa, 0x50, 0xbd, 0xe8, 0xad, 0x36, 0x0f, 0x0d, 0xb6, 0x49, 0x49,
	0x63, 0xc0, 0xbf, 0x97, 0x3c, 0x93, 0xa3, 0x7b, 0xca, 0xcc, 0xf0, 0x66, 0x32, 0x0c, 0x5c, 0x79,
	0x47, 0xe3, 0xa8, 0x17, 0xe1, 0x69, 0xf8, 0x94, 0x99, 0x84, 0x1b, 0x39, 0x3b, 0xeb, 0xad, 0x5c,
	0xc8, 0x05, 0x3d, 0x90, 0x60, 0x86, 0x55, 0xa2, 0xe7, 0xbb, 0xe3, 0x2e, 0x63, 0x55, 0xb2, 0x6c,
	0x9f, 0xa0, 0x7a, 0xfe, 0x33, 0xe1, 0x19, 0x94, 0xca, 0x4e, 0xbd, 0x36, 0x6d, 0x71, 0x59, 0xec,
	0x36, 0x5d, 0x62, 0x88, 0xb0, 0x36, 0xfd, 0x44, 0xed, 0x8a, 0x55, 0xc6, 0xd8, 0x42, 0x15, 0xc8,
	0x2d, 0xda, 0x9a, 0xf6, 0x94, 0xe5, 0x4c, 0xb7, 0xaf, 0x50, 0xa7, 0xc0, 0x47, 0xab, 0x08, 0xf7,
	0x90, 0x4b, 0x71, 0x6a, 0x7d, 0x68, 0x44, 0xee, 0x9c, 0xce, 0xba, 0x7c, 0x80, 0x17, 0xb0, 0x8e,
	0xcd, 0xf8, 0xa3, 0xfa, 0x00, 0x82, 0x6b, 0xc6, 0x94, 0x8e, 0xf5, 0xbd, 0x84, 0xcd, 0x43, 0x20,
	0xe3, 0x5f, 0x7e, 0x66, 0x42, 0x80, 0x72, 0x70, 0xd4, 0x7b, 0x6a, 0x4e, 0x22, 0x56, 0x34, 0x92,
	0xa7, 0xa6, 0x88, 0xf8, 0x7b, 0x56, 0x51, 0x5f, 0xdd, 0x5f, 0xbf, 0xfd, 0x3f, 0xdf, 0xd7, 0x47,
	0x1e, 0xef, 0x2e, 0xbd, 0xef, 0x25, 0x4f, 0x72, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x36, 0xe4,
	0xd1, 0xaf, 0x74, 0x01, 0x00, 0x00,
}
