// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trellis.tech/trellis.v1/proto/service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_create EventType = 0
	EventType_delete EventType = 1
	EventType_update EventType = 2
)

var EventType_name = map[int32]string{
	0: "create",
	1: "delete",
	2: "update",
}

var EventType_value = map[string]int32{
	"create": 0,
	"delete": 1,
	"update": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_462d1b47d56d4d85, []int{0}
}

type Service struct {
	// @gotags: yaml:"domain,omitempty"
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty" yaml:"domain,omitempty"`
	// @gotags: yaml:"name,omitempty"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" yaml:"name,omitempty"`
	// @gotags: yaml:"version,omitempty"
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty" yaml:"version,omitempty"`
	// API Handler name  @gotags: yaml:"topic,omitempty"
	Topic                string   `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty" yaml:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_462d1b47d56d4d85, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterEnum("service.EventType", EventType_name, EventType_value)
	proto.RegisterType((*Service)(nil), "service.Service")
}

func init() {
	proto.RegisterFile("trellis.tech/trellis.v1/proto/service.proto", fileDescriptor_462d1b47d56d4d85)
}

var fileDescriptor_462d1b47d56d4d85 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x31, 0xab, 0xc2, 0x30,
	0x14, 0x46, 0x5f, 0xfb, 0xfa, 0x5a, 0x7a, 0xa7, 0x12, 0x1e, 0x92, 0x51, 0x9c, 0x44, 0xb1, 0x41,
	0x1c, 0xdd, 0x04, 0xff, 0x80, 0x3a, 0xb9, 0xd5, 0xf4, 0xa2, 0xc1, 0x36, 0x09, 0xe9, 0x35, 0xe0,
	0xbf, 0x97, 0xa6, 0xed, 0xe8, 0xf4, 0x9d, 0x73, 0xb6, 0x0f, 0xd6, 0xe4, 0xb0, 0x69, 0x54, 0x57,
	0x12, 0xca, 0x87, 0x98, 0xc4, 0x6f, 0x85, 0x75, 0x86, 0x8c, 0xe8, 0xd0, 0x79, 0x25, 0xb1, 0x0c,
	0xc6, 0xb2, 0x51, 0x17, 0x08, 0xd9, 0x79, 0x40, 0x36, 0x83, 0xb4, 0x36, 0x6d, 0xa5, 0x34, 0x8f,
	0xe6, 0xd1, 0x32, 0x3f, 0x8d, 0xc6, 0x18, 0x24, 0xba, 0x6a, 0x91, 0xc7, 0xa1, 0x06, 0x66, 0x1c,
	0x32, 0x8f, 0xae, 0x53, 0x46, 0xf3, 0xdf, 0x90, 0x27, 0x65, 0xff, 0xf0, 0x47, 0xc6, 0x2a, 0xc9,
	0x93, 0xd0, 0x07, 0x59, 0x09, 0xc8, 0x8f, 0x1e, 0x35, 0x5d, 0xde, 0x16, 0x19, 0x40, 0x2a, 0x1d,
	0x56, 0x84, 0xc5, 0x4f, 0xcf, 0x35, 0x36, 0x48, 0x58, 0x44, 0x3d, 0xbf, 0x6c, 0xdd, 0xf7, 0xf8,
	0xb0, 0xb9, 0x7e, 0xff, 0xf3, 0xbc, 0x4f, 0x6f, 0xf6, 0xe3, 0xde, 0xd2, 0x70, 0x6b, 0xf7, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x5f, 0xdc, 0xa9, 0x66, 0x05, 0x01, 0x00, 0x00,
}
