
project:
  services:
    component_ping:
      name: component_ping
      version: ${version}
    component_pong: ${component_pong}


version: v1

component_pong:
  name: component_pong
  version: ${version}